"""Add index to verdict

Revision ID: 2f7fa2584304
Revises: ae3bc3b2e389
Create Date: 2026-09-01 18:03:11.182057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7fa2584304'
down_revision: Union[str, Sequence[str], None] = 'ae3bc3b2e389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_reports', 'hybrid_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0-1 blend of model, measurement, physics and source',
               existing_nullable=True)
    op.alter_column('weather_reports', 'hybrid_signals',
               existing_type=sa.TEXT(),
               comment='JSON breakdown of contributing signals',
               existing_nullable=True)
    op.alter_column('weather_reports', 'verdict',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment='fake | suspect | ok | unchecked',
               existing_nullable=True)
    op.create_index(op.f('ix_weather_reports_hybrid_score'), 'weather_reports', ['hybrid_score'], unique=False)
    op.create_index(op.f('ix_weather_reports_verdict'), 'weather_reports', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_reports_verdict'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_hybrid_score'), table_name='weather_reports')
    op.alter_column('weather_reports', 'verdict',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='fake | suspect | ok | unchecked',
               existing_nullable=True)
    op.alter_column('weather_reports', 'hybrid_signals',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON breakdown of contributing signals',
               existing_nullable=True)
    op.alter_column('weather_reports', 'hybrid_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0-1 blend of model, measurement, physics and source',
               existing_nullable=True)
    # ### end Alembic commands ###
