"""add hybrid_updated_at

Revision ID: 47e44cb7ae68
Revises: 2f7fa2584304
Create Date: 2026-09-01 22:31:38.089651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e44cb7ae68'
down_revision: Union[str, Sequence[str], None] = '2f7fa2584304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_reports', sa.Column('hybrid_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_reports', 'hybrid_updated_at')
    # ### end Alembic commands ###
