"""add index on ml_status and source

Revision ID: 6d8bf6b36ed1
Revises: 47e44cb7ae68
Create Date: 2026-09-01 22:52:13.568212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8bf6b36ed1'
down_revision: Union[str, Sequence[str], None] = '47e44cb7ae68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ml_status_source', 'weather_reports', ['ml_status', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ml_status_source', table_name='weather_reports')
    # ### end Alembic commands ###
