"""Init

Revision ID: bd3b5da79a7d
Revises: 
Create Date: 2026-08-24 15:44:53.866938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd3b5da79a7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_post_id', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('text_clean', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_raw', sa.String(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('event_category_guess', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=False),
    sa.Column('is_likely_duplicate', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='mlstatusenum'), nullable=False),
    sa.Column('ml_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ml_event_category', sa.String(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('fake_probability', sa.Float(), nullable=True),
    sa.Column('duplicate_probability', sa.Float(), nullable=True),
    sa.Column('ml_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_reports_city'), 'weather_reports', ['city'], unique=False)
    op.create_index(op.f('ix_weather_reports_dedup_hash'), 'weather_reports', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_weather_reports_event_category_guess'), 'weather_reports', ['event_category_guess'], unique=False)
    op.create_index(op.f('ix_weather_reports_id'), 'weather_reports', ['id'], unique=False)
    op.create_index(op.f('ix_weather_reports_ingested_at'), 'weather_reports', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_weather_reports_ml_event_category'), 'weather_reports', ['ml_event_category'], unique=False)
    op.create_index(op.f('ix_weather_reports_ml_status'), 'weather_reports', ['ml_status'], unique=False)
    op.create_index(op.f('ix_weather_reports_posted_at'), 'weather_reports', ['posted_at'], unique=False)
    op.create_index(op.f('ix_weather_reports_source'), 'weather_reports', ['source'], unique=False)
    op.create_index(op.f('ix_weather_reports_state'), 'weather_reports', ['state'], unique=False)
    op.create_index(op.f('ix_weather_reports_verification_status'), 'weather_reports', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_reports_verification_status'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_state'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_source'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_posted_at'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_ml_status'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_ml_event_category'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_ingested_at'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_id'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_event_category_guess'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_dedup_hash'), table_name='weather_reports')
    op.drop_index(op.f('ix_weather_reports_city'), table_name='weather_reports')
    op.drop_table('weather_reports')
    # ### end Alembic commands ###
